---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
    - name: Add repository
      apt_repository:
        repo: "deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen"
        state: present

    - name: Install mongodb
      apt:
        pkg: mongodb-org
        state: present
    - name: Enable mongodb service
      service:
         name: mongodb
         enabled: true

  handlers:
    - name: start mongodb
      service:
        name: mongodb
        state: started
