---
- name: Install Git && Ruby && Bundler
  apt:
    update_cache: yes
    name: ['git', 'ruby-full', 'ruby-bundler', 'build-essential']
    state: present
- name: Install Bundler
  command: bash -lc "gem install bundler -v '1.16.6'"
