---
- name: Configure App
  hosts: app
  become: true
  vars:
    db_host: 10.128.0.15
  tasks:
    - name: Install packages for app server
      apt:
        name: ['git', 'ruby-full', 'ruby-bundler', 'build-essential']
        state: present

    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
    - name: reload puma
      become: true
      systemd: name=puma state=restarted
